//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pepper.Resx {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pepper.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter value here.
        /// </summary>
        internal static string ApiKey_Marvel_Private {
            get {
                return ResourceManager.GetString("ApiKey_Marvel_Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter value here.
        /// </summary>
        internal static string ApiKey_Marvel_Public {
            get {
                return ResourceManager.GetString("ApiKey_Marvel_Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter value here.
        /// </summary>
        internal static string ApiKey_Tumblr {
            get {
                return ResourceManager.GetString("ApiKey_Tumblr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a marvelentertainment.
        /// </summary>
        internal static string blogname_Tumblr {
            get {
                return ResourceManager.GetString("blogname_Tumblr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data provided by Marvel. © 2014 Marvel.
        /// </summary>
        internal static string Marvel_Attributtion {
            get {
                return ResourceManager.GetString("Marvel_Attributtion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://marvel.wikia.com.
        /// </summary>
        internal static string Url_MarvelWikia {
            get {
                return ResourceManager.GetString("Url_MarvelWikia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://feeds.feedburner.com/marvelcomics.
        /// </summary>
        internal static string Url_Rss {
            get {
                return ResourceManager.GetString("Url_Rss", resourceCulture);
            }
        }
    }
}
